### ISSUE TITLE
Taskpool completion callback can only be set once

### ISSUE THREAD

**Issue by abouteiller** [ICLDisco/parsec#160]
**[Original report](https://bitbucket.org/icldistcomp/parsec/issue/160) by Reazul Hoque (Bitbucket: [rhoque_icl](https://bitbucket.org/rhoque_icl), ).**

----------------------------------------

Callback on completion of a taskpool can only be set once. Either this behavior should be enforced(by a warning message) or should be fixed(allowing overwriting the callback).
[Check Here](https://bitbucket.org/icldistcomp/parsec/src/master/parsec/parsec.c?fileviewer=file-view-default#parsec.c-1624)

**Comment by therault** [comment]
Proposed solution: add a function to reset the callback to NULL (this function should return the old callback), so that DSLs like DTD can change the callback multiple times, but if a DSL just try to overwrite the current callback, this ends up in a warning/error.

**Comment by abouteiller** [comment]
We changed our minds, we just want to allow it to be changed without verification.
