### ISSUE TITLE
Libraries and runtimes using PaRSEC need a parsec_taskpool_wait interface

### ISSUE THREAD

**Issue by abouteiller** [ICLDisco/parsec#294]
**[Original report](https://bitbucket.org/icldistcomp/parsec/issue/294) by Thomas Herault (Bitbucket: [herault](https://bitbucket.org/herault), GitHub: [therault](https://github.com/therault)).**

----------------------------------------

dplasma uses parsec\_context\_wait\(\) to wait for the completion of its blocking interface functions;

MADNESS uses parsec\_context\_wait\(\) to wait for the completion of all the tasks it submitted in its fence\(\);

These do not interface well, as dplasma shouldn’t wait for the completion of MADNESS tasks, and MADNESS should not care about the dplasma blocking interface functions…

They should wait however on the specific taskpool they both created.

But we don’t provide a parsec\_taskpool\_wait function at the time

**Comment by bosilca** [comment]
We have this functionality in TESSE but we need to move it back into master. @therault volunteered.

**Comment by bosilca** [comment]
Code implemented in #411.

**Comment by abouteiller** [comment]
#411 merged
