### ISSUE TITLE
ptgpp targets compiled when BISON not found

### ISSUE THREAD

**Issue by abouteiller** [ICLDisco/parsec#301]
**[Original report](https://bitbucket.org/icldistcomp/parsec/issue/301) by Anonymous.**

----------------------------------------

I am trying to install Parsec on a raspberry pi. When compiling I get this error:

('Installed Python Trace Tables module to', 'lib.linux-aarch64-2.7')
[ 15%] Built target target
make[2]: *** No rule to make target '../parsec/data_dist/matrix/parsec_ptgpp', needed by 'parsec/data_dist/matrix/diag_band_to_rect.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1764: parsec/data_dist/matrix/CMakeFiles/parsec_data_matrix.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

Here is the output of cmake:

pi@court4:~/pastix/parsec/build $ cmake .. -DCMAKE_INSTALL_PREFIX=${PARSEC_DIR}
-- Could NOT find BISON (missing: BISON_EXECUTABLE)
-- Building for target aarch64
-- Looking for include file stdatomic.h
-- Looking for include file stdatomic.h - found
--       support for 32 bits atomics - found
--       support for 64 bits atomics - found
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY)
-- Fortran adds libraries path /lib/arm-linux-gnueabihf;/usr/lib/gcc/arm-linux-gnueabihf/8;/usr/lib/arm-linux-gnueabihf;/usr/lib
-- Fortran adds libraries gfortran;m;gcc_s;gcc;m;gcc_s;gcc;c;gcc_s;gcc
-- LINK_DIRECTORIES = /lib;/lib32;/lib64;/usr/lib;/usr/lib32;/usr/lib64
-- INSTALL_PREFIX = /lib
CMake Warning (dev) at CMakeLists.txt:808 (set):
  implicitly converting 'List of directories used to compile the parsec_ptgpp
  generated code' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find GTG (missing: GTG_LIBRARY GTG_INCLUDE_DIR)
-- Checking for module 'libgvc'
--   Found libgvc, version 2.40.1
-- Found GRAPHVIZ: /usr/lib/arm-linux-gnueabihf/libgvc.so;/usr/lib/arm-linux-gnueabihf/libcgraph.so;/usr/lib/arm-linux-gnueabihf/libcdt.so;/usr/lib/arm-linux-gnueabihf/libpathplan.so
-- Cython version 0.29.2 found
-- PARSEC Modular Component Architecture (MCA) discovery:
-- -- Found Component `pins'
-- ---- Module `iterators_checker' is ON
-- The PAPI Library is found at PAPI_LIBRARY-NOTFOUND
-- Module papi not selectable: PARSEC_PROF_TRACE disabled.
-- ---- Module `print_steals' is ON
-- ---- Module `ptg_to_dtd' is ON
-- Module task_profiler not selectable: PARSEC_PROF_TRACE disabled.
-- Component pins sources: mca/pins/pins.c;mca/pins/pins_init.c
-- -- Found Component `sched'
-- ---- Module `ap' is ON
-- ---- Module `gd' is ON
-- ---- Module `ip' is ON
-- ---- Module `lfq' is ON
-- ---- Module `lhq' is ON
-- ---- Module `ll' is ON
-- ---- Module `ltq' is ON
-- ---- Module `pbq' is ON
-- ---- Module `rnd' is ON
-- ---- Module `spq' is ON
-- Component sched sources:
-- PARSEC Modular Component Architecture (MCA) discovery done.
-- Internal PaRSEC does not use CAS 128B. Keeping parsec_options.h unchanged

Configuration flags:
  CMAKE_C_FLAGS          =  -std=c1x
  CMAKE_C_LDFLAGS        =
  CMAKE_EXE_LINKER_FLAGS =
  EXTRA_LIBS             = -lpthread;/usr/lib/arm-linux-gnueabihf/libdl.so;/usr/lib/arm-linux-gnueabihf/libhwloc.so;-L/lib/arm-linux-gnueabihf;-L/usr/lib/gcc/arm-linux-gnueabihf/8;-L/usr/lib/arm-linux-gnueabihf;-L/usr/lib;gfortran;m;gcc_s;gcc;m;gcc_s;gcc;c;gcc_s;gcc

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/pastix/parsec/build

**Comment by abouteiller** [comment]
Thomas' comment should have solved it

**Comment by abouteiller** [comment]
This is not quite correct: when BISON is not found (or an invalid version of BISON, e.g., on macOS X), the PTG DSL should not compile, but it should not break down. 

We need to either: 
1. `find_package(BISON 3 REQUIRED)`
2. make it compile everything -but- the PTG DSL and related tests.

**Comment by bosilca** [comment]
I had a branch for this, I need to move it from bitbucket and create a PR.
