### ISSUE TITLE
Re-enable the api/operator:mp test

### ISSUE THREAD

**Issue by bosilca** [ICLDisco/parsec#319]
**Describe the bug**
The api/operator:mp test is regularly failing. I will disable it to allow github actions to be merged (#309), but we need to find the bug, fix it and then enable this test again.

**To Reproduce**
Any type of build run the test multiple times and it will eventually deadlock.

**Comment by bosilca** [comment]
check if the parsec map operator is up2date.

**Comment by abouteiller** [comment]
Just ran operator:mp on histamine for 1000 times without a fail. Let's call this fixed.
