### ISSUE TITLE
Profiling: trouble with PAPI SDE

### ISSUE THREAD

**Issue by omor1** [ICLDisco/parsec#369]
## Describe the bug
#365 fixed several issues with PAPI SDE, but I still seem to be having trouble getting PAPI SDE working.

### To Reproduce
I've back-ported this commit to my branch and am running HiCMA with `--mca profile_keys 1024 --mca mca_pins task_profiler,papi --mca pins_papi 1 --mca pins_papi_event "S*:C*:F1:MAB_ALLOCATION_BY_PIPE:HW_PF,S*:C*:F1:MAB_ALLOCATION_BY_PIPE:ST_PIPE,S*:C*:F1:MAB_ALLOCATION_BY_PIPE:DATA_PIPE,S0:C0:F10ms:sde:::PARSEC::TASKS_ENABLED,S0:C0:F10ms:sde:::PARSEC::TASKS_RETIRED"`. The events requested are:

- `S*:C*:F1:MAB_ALLOCATION_BY_PIPE:HW_PF`
- `S*:C*:F1:MAB_ALLOCATION_BY_PIPE:ST_PIPE`
- `S*:C*:F1:MAB_ALLOCATION_BY_PIPE:DATA_PIPE`
- `S0:C0:F10ms:sde:::PARSEC::TASKS_ENABLED`
- `S0:C0:F10ms:sde:::PARSEC::TASKS_RETIRED`

The first three measure cache misses by the hardware prefetched, stores, and loads on all compute threads before/after each task. The last two measure tasks enabled and retired; I want to measure only on one compute thread and every 10ms to coarsen the measurements.

On each process, I get the error message(s):
```
failed to add event sde:::PARSEC::TASKS_ENABLED; ERROR: Invalid argument
failed to add event sde:::PARSEC::TASKS_RETIRED; ERROR: Invalid argument
```

### Expected behavior
PaRSEC should add and record the requested events.

## Environment (please complete the following information):
 - PaRSEC version: branch from the communication engine work, with 85192bc090204814ab535fd705de1d487b90195c cherry-picked
 - OS: Rocky Linux 8.5
 - Compiler: AMD clang version 12.0.0
 - MPI version: N/A

## Additional context
[`papi_native_avail` output](https://github.com/ICLDisco/parsec/files/8410885/papi_native_avail.txt)

**Comment by therault** [comment]
Can you check that your final binary is loading the right PAPI library?

This error is output by PaRSEC when `PAPI_Event_create` does not find the event, yet your output of `papi_native_avail -sde /path/to/libparsec.so` seems to imply that the event `sde:::PARSEC::TASKS_ENABLED` should be registered when using a SDE-enabled PAPI library. I'm suspecting a wrong PAPI library gets loaded in your final executable.

You can also try `papi_native_avail -sde /path/to/binary`. If that shows the event `sde:::PARSEC::TASKS_ENABLED`, then this really looks like the `libpapi.so` that you are loading at execution time does not enable SDE.

**Comment by omor1** [comment]
This doesn't appear to be the case—both indications are that the correct PAPI library is found. For the former, I run `srun ldd /path/to/binary` where I would normally launch the job (`srun /path/to/binary`) in my script. Is there some runtime option for PaRSEC to enable SDE?

**Comment by therault** [comment]
`PARSEC_PROF_TRACE=ON` and a PAPI library discovered should be enough.
If `papi_native_avail -sde /path/to/libparsec.so` shows the events, the
events should be available...

Can you copy-paste the output of `ldd /path/to/libparsec.so` and `ldd
/path/to/executable` in the thread?
Also, what is the output of `nm /path/to/libparsec.so | grep papi_sde_init`?

**Comment by omor1** [comment]
```
$ ldd /path/to/binary
        linux-vdso.so.1 (0x0000155555551000)
        libalm.so => /home/omor1/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/aocc-3.0.0-4tflgtbenvsdjuq4nzlb5n2zmvlmxf6y/lib/libalm.so (0x000015555543a000)
        libm.so.6 => /lib64/libm.so.6 (0x0000155554fa5000)
        libmkl_intel_lp64.so => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/intel-mkl-2019.5.281-zpqtt6ipholmffsnm7m7llhnajbsfhnr/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64/libmkl_intel_lp64.so (0x000015555442d000)
        libmkl_sequential.so => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/intel-mkl-2019.5.281-zpqtt6ipholmffsnm7m7llhnajbsfhnr/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64/libmkl_sequential.so (0x0000155552e14000)
        libdplasma.so.2 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/dplasma-local-jxccaqyabdl3u4fr433nrstp6hkklsdv/lib64/libdplasma.so.2 (0x0000155552768000)
        libmkl_core.so => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/intel-mkl-2019.5.281-zpqtt6ipholmffsnm7m7llhnajbsfhnr/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64/libmkl_core.so (0x000015554e437000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000015554e233000)
        libparsec.so.3 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/parsec-local-3twghxaemqjh3jjq67xg6l5qb4udlnyo/lib64/libparsec.so.3 (0x000015555537d000)
        liblci.so => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/lci-local-4bbq3gk2hdtrzbjlvvcb2hemaksb3lxd/lib64/liblci.so (0x000015554e205000)
        libhwloc.so.15 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/hwloc-2.4.1-wfxg2i4y4jxhq5bdslqeqb2pnpplvhnb/lib/libhwloc.so.15 (0x000015554e1a9000)
        libpapi.so.6.0 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/papi-6.0.0.1-ewy2v6sur4b3ieyjw252rbro4k44bby5/lib/libpapi.so.6.0 (0x000015554e133000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000015554df13000)
        libc.so.6 => /lib64/libc.so.6 (0x000015554db4e000)
        /lib64/ld-linux-x86-64.so.2 (0x0000155555327000)
        librt.so.1 => /lib64/librt.so.1 (0x000015554d946000)
        libflang.so => /home/omor1/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/aocc-3.0.0-4tflgtbenvsdjuq4nzlb5n2zmvlmxf6y/lib/libflang.so (0x000015554d542000)
        libflangrti.so => /home/omor1/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/aocc-3.0.0-4tflgtbenvsdjuq4nzlb5n2zmvlmxf6y/lib/libflangrti.so (0x000015555536a000)
        libpgmath.so => /home/omor1/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/aocc-3.0.0-4tflgtbenvsdjuq4nzlb5n2zmvlmxf6y/lib/libpgmath.so (0x000015554d0f9000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x000015554ceb8000)
        libompstub.so => /home/omor1/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/aocc-3.0.0-4tflgtbenvsdjuq4nzlb5n2zmvlmxf6y/lib/libompstub.so (0x0000155555361000)
        libibverbs.so.1 => /lib64/libibverbs.so.1 (0x000015554cc9c000)
        libpciaccess.so.0 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/libpciaccess-0.16-ont5eopurcmhmapjcdx5bezgg2pnjz56/lib/libpciaccess.so.0 (0x0000155555356000)
        libxml2.so.2 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/libxml2-2.9.10-5acdfd55xb5tbwvruxpos6mizl7hvh4b/lib/libxml2.so.2 (0x000015554cb14000)
        libpfm.so.4 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/papi-6.0.0.1-ewy2v6sur4b3ieyjw252rbro4k44bby5/lib/libpfm.so.4 (0x000015554c89d000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x000015554c685000)
        libomp.so => /home/omor1/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/aocc-3.0.0-4tflgtbenvsdjuq4nzlb5n2zmvlmxf6y/lib/libomp.so (0x000015554c3b0000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x000015554c019000)
        libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x000015554bd93000)
        libnl-3.so.200 => /lib64/libnl-3.so.200 (0x000015554bb70000)
        libz.so.1 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/zlib-1.2.11-omq2fsz3fi4zex2xa2yj2lvluixsyk6x/lib/libz.so.1 (0x000015554bb56000)
        liblzma.so.5 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/xz-5.2.5-enj5mygu7xn3l4wdsuzmpqmwezveumh6/lib/liblzma.so.5 (0x000015554bb2b000)
        libiconv.so.2 => /home/omor1/spack/opt/spack/linux-centos8-zen2/aocc-3.0.0/libiconv-1.16-x7c5xwvmdon6mhug7dwmu5eqlpzyicqe/lib/libiconv.so.2 (0x000015554ba2f000)
```
(I'm not sure why `libomp` is being linked, maybe MKL pulled it in somehow?)

```
$ nm /path/to/libparsec.so | grep papi_sde_init
0000000000081f30 T parsec_papi_sde_init
```

**Comment by omor1** [comment]
So that `nm` tells me that `papi_sde_init` isn't defined as an external symbol... or a symbol at all! Which means that it's being pulled in from `sde_lib.h` and inlined...

**Comment by omor1** [comment]
@therault have you tested SDE when PaRSEC is compiled with LTO/IPO and/or high optimization levels? Using `objdump` I've verified that `papi_sde_init` is fully inlined into `parsec_papi_sde_init` (there's a `getenv` call).

**Comment by therault** [comment]
The current parsec SDE integration works with SDE as in PAPI master (a19657e)... I have checked with the developers of PAPI, but it's unclear if this is compatible with SDE in papi-6.0.0.1 as provided by your spack install...

Can you compile and install PAPI from https://bitbucket.org/icl/papi/src/master/ ?

**Comment by omor1** [comment]
I haven't verified that the relevant SDE statistics exist in the profile\*, but PAPI no longer complains about not knowing about the event, so I'll consider this resolved. We should make sure to document that using PAPI SDE with PaRSEC now requires a development version of PAPI.

\* I run into issues when converting because I have many events that begin on one stream and end in another—in discussion with @bosilca about whether this can be improved.

**Comment by omor1** [comment]
One last note: "the **numbre** of tasks that completed at this time" 😆
