### ISSUE TITLE
Profiling: MPI_DATA_PLD_SND/MPI_DATA_PLD_RCV will mismatch end event

### ISSUE THREAD

**Issue by omor1** [ICLDisco/parsec#373]
## Describe the bug
The `MPI_DATA_PLD_SND` and `MPI_DATA_PLD_RCV` profiling events use dep index as the event id. There can be many data transfers occurring concurrently, including multiple for the same dep index for different task classes or different instances of the same task class. An end event `E` is considered to match a start event `S` when:
1. `S` and `E` have the same base key i.e. are the same event type
2. `S` and `E` have the same event identifier
3. `S` and `E` have the same taskpool id
4. `S` has a timestamp before that of `E`

In particular, when matching the _next_ matching event in the stream is assumed to be the correct match. Suppose a profiling stream has the following events:
1. Data Send Start, event id = 0 [start send for dep 0 of task A]
2. Data Send Start, event id = 0 [start send for dep 0 of task B]
3. Data Send End, event id = 0 [end send for dep 0 of task A]
4. Data Send End, event id = 0 [end send for dep 0 of task B]

Then both start events will complete with the end profiling event 3, rendering the end completion times bogus.

### To Reproduce
1. Profile communication for some PaRSEC application
2. Convert to PTT/HDF5
3. Analyze:
```python
import parsec_trace_tables as ptt
import pandas as pd
trace = ptt.from_hdf("/path/to/profile.hdf5")
trace.events.loc[lambda df: df.type == trace.event_types.at["MPI_DATA_PLD_SND"]].groupby("node_id").apply(
    lambda df: pd.Series(
        {"end": len(df.end.unique()), "begin": len(df.begin.unique()), "len": len(df)}
    )
)
```

Looking at an existing profile, I see:
| node_id |   end |  begin |    len |
|---------|-------|--------|--------|
| 0       | 44498 |  67122 |  67122 |
| 1       | 88903 | 133728 | 133728 |
| 2       | 22619 |  34049 |  34049 |
| 3       | 22701 |  33599 |  33599 |

Note that around 1/3 of the events share an end timestamp—these are mismatched!

### Expected behavior
Matching should find the correct end event; it must be possible to disambiguate between concurrent events with the same dep index. I believe that other communication profiling events do this correctly: activations are funneled through the comm thread and complete in-order (blocking `MPI_Send` is used), so using a \`0' tag is valid, though not ideal; and the data control event is similarly funneled, though it uses a monotonically incrementing counter to disambiguate events. The communication engine branch I'm using is somewhat better about this, using an atomically incrementing event id for both activations and data control events, but data send/recv is still bugged.

I'd like to keep the dep index around in some form—it's useful for analysis of _which_ data was communicated—but it is not suitable for the event id. It should probably be added to the event info, if possible.

## Environment (please complete the following information):
 - PaRSEC version: recent
 - OS: Rocky Linux 8.5 [exec], macOS 12.3.1 [analysis]
 - Compiler: AMD clang version 12.0.0
 - MPI version: N/A

**Comment by therault** [comment]
I need to look in the HDF5 to understand the issue better. Can you send it to me, or share it in this issue?

**Comment by omor1** [comment]
The HDF5s I have are all relatively large (1.5+ GB); even compressed with Zstd it's 230 ish MB. I'll upload it to a temporary repo soon, but the gist is that what you see is many `MPI_DATA_PLD_SND` events with the same end time (ditto `MPI_DATA_PLD_RCV`)—these are distinct start events that matched with the same end event.

**Comment by omor1** [comment]
@therault [dpotrf_tlr.2.1080000.3600.2x2.lci.11314009.h5](https://github.com/uiuc-hpc/parsec-profile-temp/blob/5b3fa9af7b17a0a1b1ddd60b629e3cbd57261605/dpotrf_tlr.2.1080000.3600.2x2.lci.11314009.h5)

**Comment by omor1** [comment]
I implemented a fix and now get correct results when running the above code i.e. end events are matched correctly with start events so end times are not duplicated.
| node_id |    end |  begin |    len |
|---------|--------|--------|--------|
| 0       |  67122 |  67122 |  67122 |
| 1       | 133728 | 133728 | 133728 |
| 2       |  34049 |  34049 |  34049 |
| 3       |  33599 |  33599 |  33599 |

**Comment by bosilca** [comment]
It seems as the first value is replicated across the entire row. Did I missed something ? What is the fix that you propose ?

**Comment by omor1** [comment]
> It seems as the first value is replicated across the entire row. Did I missed something ? What is the fix that you propose ?

@bosilca this is the result of counting the number of unique end times and unique begin times, as well as the total number of rows, per node. These are _supposed_ to match—since data movement is funneled through the communication thread, no two events can begin or end at the same time, so all begin and event times must necessarily be unique (per node). The problem is that they currently do _not_ match, because the end times are replicated—this is because start events are associated with the wrong end event.

My fix is bipartite:
* Generate a unique event id by incrementing a counter, as is done for other events.
* Augment the info structure and record the dep index `k`.

In my fix I split out the structure for activation message and for data movement, since the activation message would always set the dep index to something invalid and it would just waste memory and storage in the profile.

**Comment by omor1** [comment]
Note (as I just found out to my detriment) that you must take care that each dep gets its own `event_id`, otherwise it can still mismatch between different deps for the same activation—particularly relevant for `MPI_DATA_PLD_RCV`.

**Comment by omor1** [comment]
#376 is one approach to fixing the problem; I used a different one in my branch, but as long as different communications are disambiguated, everything should be fine.
