### ISSUE TITLE
Imbalanced communications due to broadcast topologies

### ISSUE THREAD

**Issue by omor1** [ICLDisco/parsec#466]
## Description
When descendants of a task are located on multiple remote nodes, the associated activations and data follow a broadcast tree topology. The exact topology depends on the PaRSEC configuration—star, chain/pipeline, and binomial trees are all supported—but assuming a non-star topology is used, remote nodes within the topology are implicitly ordered by their rank: if rank 0 is included in the broadcast then it will always by the first destination, while rank N-1 will be the last.

This ordering means that even if a computation is balanced and that each node generates the same amount of outgoing data, communications overall are quite imbalanced. Rank N-1 will only send to another node if it is the root of a broadcast, while rank 0 will need to forward activations and data in every broadcast in which it is a participant. The ordering also means that in terms of latency from when a task completes to when descendant tasks on remote nodes are able to start, tasks located on lower-ranked nodes will be able to start sooner than those on higher-ranked nodes; if a computation is highly sensitive to latency, this can lead to greater starvation on some nodes than others due solely due to this broadcast topology ordering.

Both these behaviors are observable. A plot of communication volume over time is below. This particular plot was from HiCMA over PaRSEC using LCI as a communication backend, but similar behavior is observed with MPI. Note how nodes 12–15 receive much more data than they send, up to twice as much for this problem size.
![lci_communication](https://user-images.githubusercontent.com/4326436/209239452-3e1b4429-f88a-43cc-b7dc-ae24e811ac2a.png)
I am also working on obtaining hard numbers for the duration of communication from the root of the broadcast to each of its destination. While my current statistics are unreliable due to significant clock skew between nodes, they are sufficient for me to be highly confidant that the mean latency is several times higher on higher-ranked nodes.

### Describe the solution you'd like
Broadcast topologies should not use a static ordering, so as to distribute the communication load better. The simplest solution is to order using the root as a basis point—some details are described below.

### Describe alternatives you've considered
There are plenty of ways to order the ranks; some ordering mechanisms include:
* Order participating ranks starting from the root. This means that e.g. a broadcast containing ranks {1, 3, 8, 9} as destinations would be ordered (1, 3, 8, 9) if the root is rank 0 (or rank 10), but ordered (8, 9, 1, 3) if the root is rank 4–7. Since the broadcast is already aware of the root, no additional information is necessary in the activation message.
* Order participating ranks entirely randomly. This likely incurs some overhead, as the chosen order would need to be transported along with the activation.
* Order participating ranks starting from a randomly-chosen rank. This only requires transporting the chosen offset, so adds ~4 bytes.
* Order participating ranks starting from rank with highest-priority successor task. Similar to the above, this only requires transporting the chosen offset, so adds ~4 bytes. It may be possible to recompute this on each successor rank in the broadcast, at the cost of additional computation; this is unlikely to be worthwhile.
* Order participating ranks entirely by the maximum priorities of the successor tasks on each rank. This requires either transporting the order along with the data or recalculating the order at each descendent rank—which is better may depend on the algorithm, data distribution, and number of nodes.

There are doubtlessly other ways to order the ranks; I simply propose these as possibilities. The random ordering is algorithmically elegant as it should, on average, give a good broadcast ordering distribution regardless of the application or its data distribution; however, due to its nature, has poorer reproducibility.

## Additional context
I've discussed the issue previously with @bosilca.
Most applications using PaRSEC are written such so this isn't a huge factor, or use a sufficiently large problem size that starvation due to communication latency isn't a significant concern. I've uncovered this as an issue in my work with the LCI backend, as demonstrating communication improvements naturally requires running problems where PaRSEC isn't necessarily able to fully overlap communication latencies with additional computation.

**Comment by omor1** [comment]
Some additional plots demonstrating the problem are below.

### Mean root-to-destination latency is correlated with rank id
Demonstrating that mean time between when data is available at the broadcast root and when it is available at each node increases with rank id. Note that the mean time between when the immediate predecessor sends the data to when it is received does not vary significantly with rank id, so this effect can be ascribed to how ranks are ordered in the broadcast.
<img height="350" alt="image" src="https://user-images.githubusercontent.com/4326436/213565215-f125decc-9930-4d2a-b7a2-88f7cb1e54f0.png"><img height="350" alt="image" src="https://user-images.githubusercontent.com/4326436/213565304-a5f2587e-dee7-4d1b-9bcb-cb654f05e8b1.png">

### High-rank nodes send less data
Demonstrating that send volume and count decreases drastically at ranks 12–15 as they are almost always leaves in the broadcast tree.
<img height="350" alt="image" src="https://user-images.githubusercontent.com/4326436/213566205-841bb656-4367-478c-b36b-69d265ad9ef1.png"><img height="350" alt="image" src="https://user-images.githubusercontent.com/4326436/213566219-c0ac0e7c-3528-425a-a3ba-98ffee69d3ba.png">

**Comment by abouteiller** [comment]
475502ad should have resolved this. Omri please reopen if not the case.

**Comment by omor1** [comment]
> [475502a](https://github.com/ICLDisco/parsec/commit/475502ad7bea6b312840df24f3913bb9b86eb892) should have resolved this. Omri please reopen if not the case.

Yup, that should fix this particular issue.

The infrastructure will need to be reworked a bit once I get the code in a mergeable state for rotating the bcast around the node with the highest-priority task, since to get that working I needed to use an entirely different method; doing so might (re)introduce some imbalance if high-priority tasks aren't distributed equally, but overall performance should be improved for algorithms, due to high-priority tasks consistently receiving data first.
