### ISSUE TITLE
MPICC does not compile profiling tools by default.

### ISSUE THREAD

**Issue by v0dro** [ICLDisco/parsec#470]
## Describe the bug
Using `CC=mpicc` with `--enable-prof-trace` does not enable profiling tools by default.

### To Reproduce
On the master branch in the `build/` directory use the following configure line

```
CC=mpicc ./configure  --prefix=/home/sameer.deshmukh/gitrepos/parsec/build --without-cuda --enable-prof-trace --enable-debug=noisier --with-papi -DPARSEC_PROF_TRACE_SYSTEM="PaRSEC Binary Tracing Format"
```

### Expected behavior
It should produce the HDF5 conversion binaries in the `bin/` folder, but does not.

## Environment (please complete the following information):
 - PaRSEC version: 68ada9e23dc5242e72c6575fa7f258f5f92dbbc7
 - OS: Ubuntu
 - Compiler:GCC 8.4
 - MPI version: OpenMPI 4.0.5

**Comment by therault** [comment]
The issue we found with Sameer was that `tools/profiling/python/setup.py.in` checks if `compiler.endswith('icc')` and it then adds some flags to the command line. However, `mpicc` ends with `icc`... Even if `mpicc` is using `gcc` as a compiler... And the flags added to the compile line by `setup.py` are only compatible with Intel Compiler.

A quick fix consisted in saying `if compiler.endswith('icc') and not compiler.endswith('mpicc'):` but this is incorrect if `mpicc` is using `icc`.

We should use the string output by `${compiler} --version` to detect if it's Intel or not...
