### ISSUE TITLE
profile2h5 out of memory for large traces

### ISSUE THREAD

**Issue by DSMishler** [ICLDisco/parsec#507]
## Profile2h5 can't handle traces that are too large

I was on xsdk and ran a dgemm with profiling on dplasma. `./testing_dgemm -N 48000 -nruns 3`. I opened the trace file and tried to run `profile2h5` as per the profiling guide. `profile2h5 2023-03-20_xsdk_ts200_N48000_ptg_lfq.prof` (that was the name of my trace file). After waiting many minutes, it runs out of memory. This might just be a profile2h5 issue, but want to report anyway.

**Comment by bosilca** [comment]
A 48000 matrix with a tile size of 200 has 240 tiles per dimension. If we only count the tasks we have $240^3$ events per run, so with your `nruns = 3` we are talking tens of GB of raw data in the file. Unwrapped as a tables in memory this is quite a significant amount, so it makes sense that you are running out of space. We could fix it, which represent a lot of work with questionable benefits, or you could try to only profile one of your runs. The profiling has an `on/off` interface that allows you to only profile a section of the code.

**Comment by DSMishler** [comment]
I like running with profiling `off`. I should try that, for one and only save the last run. I agree wtih Omri that `--ptt-version 2` should work, but it's clear that the issue is on the trace file size. I was trying a trace this large to inspect other issues that report missing events, but I think that the way I'll do that is with `--ptt-version 2` and with smarter tracing. I agree with George, this issue would require a lot of work and I don't think it's worth it. We can close this issue and I'll see what I can do with what both of you have suggested.
