### ISSUE TITLE
MPI_AND_HWLOC_COMPATIBLE needs some optional deactivation

### ISSUE THREAD

**Issue by therault** [ICLDisco/parsec#511]
## Describe the bug

On some machines (e.g. summit when using spectrum-mpi), one cannot run an MPI program without a reservation, and singleton runs do not seem to be supported. (singleton runs on summit complain that no run environment is setup; mpirun -n 1 of the MPI program complains about running without reservation).

This might be considered a bug in the MPI environment, but as a result configuring PaRSEC is impossible without editing CMakeLists.txt.

### To Reproduce
Run cmake on summit with spectrum-mpi as the MPI.

### Expected behavior
It would be better to display an error message and provide some hints to the user on how to check that their HWLOC environment is compatible with their MPI environment, and then to give them the option to affirm to cmake that they are compatible.

### Proposal:

Produce the test file, compile it, and try to run it. If the run fails, keep the test file and the compiled file, and ask the user to run it and check the output. If the output is correct, instruct the user to run with some option (e.g. `-DMPI_HWLOC_COMPATIBLE=TRUE`) to bypass the automatic test in CMakeLists.txt.

**Comment by abouteiller** [comment]
This in general is why we don't like run-tests. Normally that should be handled with the same mechanisms we use for cross-compiling. Let me dig how it's done and maybe we can add a useful guidance about that in the error output.

**Comment by bosilca** [comment]
e4a3924218 right ?

**Comment by abouteiller** [comment]
8415fa43
