### ISSUE TITLE
CMake fails if 128bit integer are detected but 128bit CAS is not lock-free

### ISSUE THREAD

**Issue by devreal** [ICLDisco/parsec#709]
## Describe the bug

Getting this error in a x86-64 docker container on an Apple M3:

```
-- Check offset of field lifo_private in structure 'struct{parsec_object_t super;uint8_t alignment; union{int64_t i64; char lifo_private;};}'
-- Check offset of field lifo_private in structure struct{parsec_object_t super;uint8_t alignment; union{int64_t i64; char lifo_private;};} - failed
CMake Error at CMakeLists.txt:1140 (message):
  Cannot determine the offset of the lifo_private field in PaRSEC LIFO
  structure.  Assume something is wrong with the compilation and need to be
  fixed before continuing.
```

Looking at the CMake log it seems that we find 128bit integer support and 128bit CAS but that it is not lock-free. We then proceed down the rabbit hole, trying `__sync` primitives and eventually ending up with lock-based atomics, which then fails the lifo check. I'm attaching the CMake log.

[CMakeConfigureLog.yaml.gz](https://github.com/user-attachments/files/17870932/CMakeConfigureLog.yaml.gz)

### Expected behavior

We should stick with C11 atomic for 32/64 atomics and disable 128bit support.

## Environment (please complete the following information):

Docker container with x86-64 Ubuntu 24.04 on a Apple M3 hardware with gcc 13.2 or clang 18.

**Comment by abouteiller** [comment]
It is highly probable that running with 64bit atomics is slower than running with x86 128bit (-mcx16) in many cases with real x86 hardware (and we do fallback to that setup on many machines due to not passing -mtune=xyz, where xyz is better than Haswell or around).

Why does the alignment fails when we use fallback? Is it because not only we fail the c11, but also the x86 cx16?

**Comment by devreal** [comment]
Ahh snap. Had a typo in list.h so that's why the check failed 🤦
